# Generated by Django 4.1.1 on 2022-09-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField()),
                ('durasi_nyusu', models.FloatField()),
                ('catatan_nyusu', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField()),
                ('bab', models.CharField(choices=[('Yes', 'Ya'), ('No', 'Tidak')], default='No', max_length=3)),
                ('tekstur_bab', models.CharField(blank=True, max_length=100)),
                ('warna_bab', models.CharField(blank=True, max_length=100)),
                ('catatan_diaper', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField()),
                ('makanan', models.CharField(max_length=200)),
                ('porsi_suapan', models.FloatField()),
                ('durasi_makan', models.FloatField(blank=True)),
                ('catatan_makan', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField()),
                ('berat_badan', models.FloatField()),
                ('tinggi_badan', models.FloatField()),
                ('lingkar_kepala', models.FloatField(blank=True)),
                ('suhu_tubuh', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hygiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField()),
                ('mandi', models.CharField(choices=[('Morning', 'Pagi'), ('Evening', 'Sore'), ('Emergency', 'Darurat')], max_length=10)),
                ('durasi_mandi', models.FloatField(blank=True)),
                ('merk_sabun', models.CharField(max_length=50)),
                ('jenis_air', models.CharField(choices=[('Normal', 'Dingin'), ('Warm', 'Hangat')], default='Warm', max_length=6)),
                ('gosok_kepala', models.CharField(choices=[('Yes', 'Ya'), ('No', 'Tidak')], default='Yes', max_length=3)),
                ('gosok_gigi', models.CharField(choices=[('Yes', 'Ya'), ('No', 'Tidak')], default='Yes', max_length=3)),
                ('gosok_lidah', models.CharField(choices=[('Yes', 'Ya'), ('No', 'Tidak')], default='Yes', max_length=3)),
                ('catatan_mandi', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField()),
                ('nama_obat', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=100)),
                ('manfaat', models.CharField(max_length=200)),
                ('vaksin', models.CharField(choices=[('Yes', 'Ya'), ('No', 'Tidak')], default='Yes', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField()),
                ('durasi_tidur', models.FloatField()),
                ('catatan_tidur', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
