# Generated by Django 4.1.1 on 2022-09-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='usia',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='general',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
    ]
