# Generated by Django 4.1.1 on 2022-09-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_general_usia_alter_general_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='breast',
            name='tipe',
            field=models.CharField(default='nyusu', max_length=20),
        ),
        migrations.AddField(
            model_name='diaper',
            name='tipe',
            field=models.CharField(default='popok', max_length=20),
        ),
        migrations.AddField(
            model_name='food',
            name='tipe',
            field=models.CharField(default='makanan', max_length=20),
        ),
        migrations.AddField(
            model_name='general',
            name='tipe',
            field=models.CharField(default='umum', max_length=20),
        ),
        migrations.AddField(
            model_name='hygiene',
            name='tipe',
            field=models.CharField(default='mandi', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='tipe',
            field=models.CharField(default='obat', max_length=20),
        ),
        migrations.AddField(
            model_name='sleep',
            name='tipe',
            field=models.CharField(default='tidur', max_length=20),
        ),
    ]
